export const inheritanceData = {
  Math: ['Object'],
  Date: ['Object'],
  Function: ['Object'],
  Object: [],
  JSON: ['Object'],
  Intl: ['Object'],
  arguments: [],
  Reflect: ['Object'],
  Proxy: [],
  Atomics: ['Object'],
};

export const groupData = {
  Error: [
    'Error',
    'EvalError',
    'InternalError',
    'RangeError',
    'ReferenceError',
    'SyntaxError',
    'TypeError',
    'URIError',
  ],
  Intl: [
    'Intl',
    'Intl.Collator',
    'Intl.DateTimeFormat',
    'Intl.ListFormat',
    'Intl.NumberFormat',
    'Intl.PluralRules',
    'Intl.RelativeTimeFormat',
    'Intl.Segmenter',
  ],
  TypedArray: [
    'TypedArray',
    'Int8Array',
    'Uint8Array',
    'Uint8ClampedArray',
    'Int16Array',
    'Uint16Array',
    'Int32Array',
    'Uint32Array',
    'Float32Array',
    'Float64Array',
    'BigInt64Array',
    'BigUint64Array',
  ],
  Proxy: ['Proxy', 'handler'],
};
