const ATTRIBUTES = [
  // 'accent-height',
  'accumulate',
  'additive',
  'alignment-baseline',
  // 'alphabetic',
  'amplitude',
  // 'arabic-form',
  // 'ascent',
  'attributeName',
  // 'attributeType',
  'azimuth',
  'baseFrequency',
  'baseline-shift',
  // 'baseProfile',
  // 'bbox',
  'begin',
  'bias',
  'by',
  'calcMode',
  // 'cap-height',
  'class',
  // 'clip',
  'clip-path',
  'clip-rule',
  'clipPathUnits',
  'color',
  'color-interpolation',
  'color-interpolation-filters',
  // 'color-profile',
  'cursor',
  'cx',
  'cy',
  'd',
  'data-*',
  'decoding',
  // 'descent',
  'diffuseConstant',
  'direction',
  'display',
  'divisor',
  'dominant-baseline',
  'dur',
  'dx',
  'dy',
  'edgeMode',
  'elevation',
  // 'enable-background',
  'end',
  'exponent',
  'fill',
  'fill-opacity',
  'fill-rule',
  'filter',
  'filterUnits',
  'flood-color',
  'flood-opacity',
  'font-family',
  'font-size',
  'font-size-adjust',
  'font-stretch',
  'font-style',
  'font-variant',
  'font-weight',
  'fr',
  'from',
  'fx',
  'fy',
  // 'g1',
  // 'g2',
  // 'glyph-name',
  // 'glyph-orientation-horizontal',
  // 'glyph-orientation-vertical',
  'gradientTransform',
  'gradientUnits',
  // 'hanging',
  'height',
  // 'horiz-adv-x',
  // 'horiz-origin-x',
  // 'horiz-origin-y',
  'href',
  'id',
  // 'ideographic',
  'image-rendering',
  'in',
  'in2',
  'intercept',
  // 'k',
  'k1',
  'k2',
  'k3',
  'k4',
  'kernelMatrix',
  'kernelUnitLength',
  // 'kerning',
  'keyPoints',
  'keySplines',
  'keyTimes',
  'lang',
  'lengthAdjust',
  'letter-spacing',
  'lighting-color',
  'limitingConeAngle',
  'marker-end',
  'marker-mid',
  'marker-start',
  'markerHeight',
  'markerUnits',
  'markerWidth',
  'mask',
  'maskContentUnits',
  'maskUnits',
  // 'mathematical',
  'max',
  'media',
  'method',
  'min',
  'mode',
  // 'name',
  'numOctaves',
  'onclick',
  'opacity',
  'operator',
  'order',
  'orient',
  // 'orientation',
  'origin',
  'overflow',
  'overline-position',
  'overline-thickness',
  'paint-order',
  // 'panose-1',
  'path',
  'pathLength',
  'patternContentUnits',
  'patternTransform',
  'patternUnits',
  'pointer-events',
  'points',
  'pointsAtX',
  'pointsAtY',
  'pointsAtZ',
  'preserveAlpha',
  'preserveAspectRatio',
  'primitiveUnits',
  'r',
  'radius',
  'refX',
  'refY',
  'repeatCount',
  'repeatDur',
  // 'requiredFeatures',
  'restart',
  'result',
  'rotate',
  'rx',
  'ry',
  'scale',
  'seed',
  'shape-rendering',
  'side',
  // 'slope',
  'spacing',
  'specularConstant',
  'specularExponent',
  'spreadMethod',
  'startOffset',
  'stdDeviation',
  // 'stemh',
  // 'stemv',
  'stitchTiles',
  'stop-color',
  'stop-opacity',
  'strikethrough-position',
  'strikethrough-thickness',
  // 'string',
  'stroke',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke-opacity',
  'stroke-width',
  'style',
  'surfaceScale',
  'crossorigin',
  'Conditional_Processing',
  'Core',
  'Events',
  'Presentation',
  'Styling',
  'systemLanguage',
  'tabindex',
  'tableValues',
  'target',
  'targetX',
  'targetY',
  'text-anchor',
  'text-decoration',
  'text-rendering',
  'textLength',
  'to',
  'transform',
  'transform-origin',
  'type',
  // 'u1',
  // 'u2',
  'underline-position',
  'underline-thickness',
  // 'unicode',
  'unicode-bidi',
  // 'unicode-range',
  // 'units-per-em',
  // 'v-alphabetic',
  // 'v-hanging',
  // 'v-ideographic',
  // 'v-mathematical',
  'values',
  'vector-effect',
  // 'version',
  // 'vert-adv-y',
  // 'vert-origin-x',
  // 'vert-origin-y',
  'viewBox',
  'visibility',
  'width',
  // 'widths',
  'word-spacing',
  'writing-mode',
  'x',
  // 'x-height',
  'x1',
  'x2',
  'xChannelSelector',
  // 'xlink:arcrole',
  // 'xlink:href',
  // 'xlink:show',
  // 'xlink:title',
  // 'xlink:type',
  // 'xml:base',
  // 'xml:lang',
  // 'xml:space',
  'y',
  'y1',
  'y2',
  'yChannelSelector',
  'z',
  // 'zoomAndPan',
];

export default ATTRIBUTES;
